CREATE TABLE CONTACORRENTE (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Cpf NVARCHAR(11) NOT NULL,
    Senha NVARCHAR(255) NOT NULL,
    Nome NVARCHAR(200) NOT NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    DataCriacao DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE MOVIMENTO (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdRequisicao NVARCHAR(100) NOT NULL,
    ContaCorrenteId INT NOT NULL,
    Valor DECIMAL(18,2) NOT NULL,
    Tipo CHAR(1) NOT NULL CHECK (Tipo IN ('C', 'D')),
    DataMovimento DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    FOREIGN KEY (ContaCorrenteId) REFERENCES CONTACORRENTE(Id)
);

CREATE TABLE TRANSFERENCIA (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdRequisicao NVARCHAR(100) NOT NULL,
    ContaOrigemId INT NOT NULL,
    ContaDestinoId INT NOT NULL,
    Valor DECIMAL(18,2) NOT NULL,
    DataTransferencia DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
