version: '3.8'

services:
  sqlite-db:
    image: alpine:latest
    container_name: ailos-sqlite
    volumes:
      - sqlite_data:/data
      - ./databases/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init-db.sh:/init-db.sh
    command: |
      sh -c "
        apk add --no-cache sqlite &&
        chmod +x /init-db.sh &&
        /init-db.sh &&
        tail -f /dev/null
      "
    networks:
      - ailos-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: ailos-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ailos-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ailos-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ailos-network

  ailos-contacorrente-api:
    build:
      context: ..
      dockerfile: src/APIs/Ailos.ContaCorrente.API/Dockerfile
    container_name: ailos-contacorrente-api
    depends_on:
      - sqlite-db
      - kafka
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/data/ailos.db
      - Kafka__BootstrapServers=kafka:29092
    volumes:
      - sqlite_data:/data
    networks:
      - ailos-network
    restart: unless-stopped

  ailos-transferencia-api:
    build:
      context: ..
      dockerfile: src/APIs/Ailos.Transferencia.API/Dockerfile
    container_name: ailos-transferencia-api
    depends_on:
      - sqlite-db
      - kafka
      - ailos-contacorrente-api
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/data/ailos.db
      - ContaCorrenteAPI__BaseUrl=http://ailos-contacorrente-api
      - Kafka__BootstrapServers=kafka:29092
    volumes:
      - sqlite_data:/data
    networks:
      - ailos-network
    restart: unless-stopped

volumes:
  sqlite_data:

networks:
  ailos-network:
    driver: bridge
